In [4]:
import pandas as pd
import numpy as np

culinary = pd.read_excel("C:/Users/eppst/OneDrive/Documents/Howard/HU - DATA302/Pauls Place Documents/Travon/Application process notes.xlsx", usecols=[4,10,17])
culinary

,Applications Submitted,# applicants who Passed Math & Reading,Goal # spots to fill
0,95,18.0,20
1,139,23.0,10
2,55,14.0,10
3,37,19.0,10
4,55,16.0,10
5,41,15.0,10
6,83,23.0,15
7,69,14.0,10
8,53,23.0,10
9,39,13.0,10
10,45,18.0,11
11,42,11.0,10
12,26,NaN,10
13,39,18.0,10
14,40,20.0,10
15,34,16.0,10
16,43,14.0,10
17,93,20.0,10

In [5]:
culinary = culinary.fillna(0)
culinary

,Applications Submitted,# applicants who Passed Math & Reading,Goal # spots to fill
0,95,18.0,20
1,139,23.0,10
2,55,14.0,10
3,37,19.0,10
4,55,16.0,10
5,41,15.0,10
6,83,23.0,15
7,69,14.0,10
8,53,23.0,10
9,39,13.0,10
10,45,18.0,11
11,42,11.0,10
12,26,0.0,10
13,39,18.0,10
14,40,20.0,10
15,34,16.0,10
16,43,14.0,10
17,93,20.0,10

In [6]:
import pandas
from sklearn import linear_model


X = culinary[['# applicants who Passed Math & Reading', 'Goal # spots to fill']]
y = culinary['Applications Submitted']

regr = linear_model.LinearRegression()
regr.fit(X.values, y.values)

# predict the # of Applications Submitted where # of applicants who Passed Math and Reading is 26 and the Goal # spots to fill is 12
predict_applications = regr.predict([[26,12]])
print(predict_applications)

[84.61451151]

In [15]:
def reg_predict():
    for i in range(10,20):  # passed math/reading
        for x in range(10,16):  # goal spots to fill
            print(f"{x}: goal spots to fill, {i}: passed math/reading, for {regr.predict([[i,x]])}: applications submitted")

In [16]:
reg_predict()

10: goal spots to fill, 10: passed math/reading, for [38.33053446]: applications submitted
11: goal spots to fill, 10: passed math/reading, for [41.64394656]: applications submitted
12: goal spots to fill, 10: passed math/reading, for [44.95735866]: applications submitted
13: goal spots to fill, 10: passed math/reading, for [48.27077076]: applications submitted
14: goal spots to fill, 10: passed math/reading, for [51.58418286]: applications submitted
15: goal spots to fill, 10: passed math/reading, for [54.89759495]: applications submitted
10: goal spots to fill, 11: passed math/reading, for [40.80910651]: applications submitted
11: goal spots to fill, 11: passed math/reading, for [44.12251861]: applications submitted
12: goal spots to fill, 11: passed math/reading, for [47.43593071]: applications submitted
13: goal spots to fill, 11: passed math/reading, for [50.74934281]: applications submitted
14: goal spots to fill, 11: passed math/reading, for [54.06275491]: applications submitted
15: goal spots to fill, 11: passed math/reading, for [57.37616701]: applications submitted
10: goal spots to fill, 12: passed math/reading, for [43.28767857]: applications submitted
11: goal spots to fill, 12: passed math/reading, for [46.60109067]: applications submitted
12: goal spots to fill, 12: passed math/reading, for [49.91450276]: applications submitted
13: goal spots to fill, 12: passed math/reading, for [53.22791486]: applications submitted
14: goal spots to fill, 12: passed math/reading, for [56.54132696]: applications submitted
15: goal spots to fill, 12: passed math/reading, for [59.85473906]: applications submitted
10: goal spots to fill, 13: passed math/reading, for [45.76625062]: applications submitted
11: goal spots to fill, 13: passed math/reading, for [49.07966272]: applications submitted
12: goal spots to fill, 13: passed math/reading, for [52.39307482]: applications submitted
13: goal spots to fill, 13: passed math/reading, for [55.70648692]: applications submitted
14: goal spots to fill, 13: passed math/reading, for [59.01989902]: applications submitted
15: goal spots to fill, 13: passed math/reading, for [62.33331111]: applications submitted
10: goal spots to fill, 14: passed math/reading, for [48.24482267]: applications submitted
11: goal spots to fill, 14: passed math/reading, for [51.55823477]: applications submitted
12: goal spots to fill, 14: passed math/reading, for [54.87164687]: applications submitted
13: goal spots to fill, 14: passed math/reading, for [58.18505897]: applications submitted
14: goal spots to fill, 14: passed math/reading, for [61.49847107]: applications submitted
15: goal spots to fill, 14: passed math/reading, for [64.81188317]: applications submitted
10: goal spots to fill, 15: passed math/reading, for [50.72339473]: applications submitted
11: goal spots to fill, 15: passed math/reading, for [54.03680683]: applications submitted
12: goal spots to fill, 15: passed math/reading, for [57.35021892]: applications submitted
13: goal spots to fill, 15: passed math/reading, for [60.66363102]: applications submitted
14: goal spots to fill, 15: passed math/reading, for [63.97704312]: applications submitted
15: goal spots to fill, 15: passed math/reading, for [67.29045522]: applications submitted
10: goal spots to fill, 16: passed math/reading, for [53.20196678]: applications submitted
11: goal spots to fill, 16: passed math/reading, for [56.51537888]: applications submitted
12: goal spots to fill, 16: passed math/reading, for [59.82879098]: applications submitted
13: goal spots to fill, 16: passed math/reading, for [63.14220308]: applications submitted
14: goal spots to fill, 16: passed math/reading, for [66.45561518]: applications submitted
15: goal spots to fill, 16: passed math/reading, for [69.76902727]: applications submitted
10: goal spots to fill, 17: passed math/reading, for [55.68053883]: applications submitted
11: goal spots to fill, 17: passed math/reading, for [58.99395093]: applications submitted
12: goal spots to fill, 17: passed math/reading, for [62.30736303]: applications submitted
13: goal spots to fill, 17: passed math/reading, for [65.62077513]: applications submitted
14: goal spots to fill, 17: passed math/reading, for [68.93418723]: applications submitted
15: goal spots to fill, 17: passed math/reading, for [72.24759933]: applications submitted
10: goal spots to fill, 18: passed math/reading, for [58.15911089]: applications submitted
11: goal spots to fill, 18: passed math/reading, for [61.47252299]: applications submitted
12: goal spots to fill, 18: passed math/reading, for [64.78593509]: applications submitted
13: goal spots to fill, 18: passed math/reading, for [68.09934718]: applications submitted
14: goal spots to fill, 18: passed math/reading, for [71.41275928]: applications submitted
15: goal spots to fill, 18: passed math/reading, for [74.72617138]: applications submitted
10: goal spots to fill, 19: passed math/reading, for [60.63768294]: applications submitted
11: goal spots to fill, 19: passed math/reading, for [63.95109504]: applications submitted
12: goal spots to fill, 19: passed math/reading, for [67.26450714]: applications submitted
13: goal spots to fill, 19: passed math/reading, for [70.57791924]: applications submitted
14: goal spots to fill, 19: passed math/reading, for [73.89133134]: applications submitted
15: goal spots to fill, 19: passed math/reading, for [77.20474344]: applications submitted

In [23]:
# redefined the function because an applicant has to pass the math/reading portion.  The number of applicants who passed math/reading
# can't be less than the number of spots to fill.
def reg_predict():
    for i in range(10,20+1):  # passed math/reading
        for x in range(i,i+1):  # goal spots to fill
            print(f"{x}: goal spots to fill, {i}: passed math/reading, for {regr.predict([[i,x]])}: applications submitted")

In [24]:
reg_predict()

10: goal spots to fill, 10: passed math/reading, for [38.33053446]: applications submitted
11: goal spots to fill, 11: passed math/reading, for [44.12251861]: applications submitted
12: goal spots to fill, 12: passed math/reading, for [49.91450276]: applications submitted
13: goal spots to fill, 13: passed math/reading, for [55.70648692]: applications submitted
14: goal spots to fill, 14: passed math/reading, for [61.49847107]: applications submitted
15: goal spots to fill, 15: passed math/reading, for [67.29045522]: applications submitted
16: goal spots to fill, 16: passed math/reading, for [73.08243937]: applications submitted
17: goal spots to fill, 17: passed math/reading, for [78.87442353]: applications submitted
18: goal spots to fill, 18: passed math/reading, for [84.66640768]: applications submitted
19: goal spots to fill, 19: passed math/reading, for [90.45839183]: applications submitted
20: goal spots to fill, 20: passed math/reading, for [96.25037598]: applications submitted